# -*- coding: utf-8 -*-
"""Day2_Anton and Letters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BANvslSBZH7zinuhjJvEQ1pyV_v-7v1v
"""

user=dict(map(int,input.split(',')))
print(user)

users=input()

letters=list(users.replace('{','').replace('}','').replace(' ','').split(','))


cheacker=[]

counter=0

for i in letters:
  if i=="":
    break
  elif i not in cheacker:
    cheacker.append(i)





print(len(cheacker))