# -*- coding: utf-8 -*-
"""Day3_Anton and Polyhedrons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BANvslSBZH7zinuhjJvEQ1pyV_v-7v1v
"""

icosahedron=20
cube=6
tetrahedron=4
dodecahedron=12
octahedron=8
counter=0

times=int(input())

for i in range(0,times):
  user=input()
  if user=="Icosahedron":
    counter+=icosahedron
  elif user=="Cube":
    counter+=cube
  elif user=="Tetrahedron":
    counter+=tetrahedron
  elif user=="Dodecahedron":
    counter+=dodecahedron
  elif user==  "Octahedron":
    counter+=octahedron
print(counter)